### ISSUE TITLE
Reorganize branches

### ISSUE THREAD

**Issue by sagikazarmark** [moneyphp/money#138]
There is a demand for a bugfix release for a long time ago. With the new version upcoming, we have to clear the state of this repository. The development branch is `nextrelease` for now, but this should be the master branch when we release the library. Since the two branches are quite far from each other, I intend to do the following (as @frederikbosch suggested):

1. Rename the current master branch to 1.x
2. Rename nextrelease to master

I really like this idea, however many other libraries are using this one, many of them rely on the master branch. With this change those won't work anymore. Should we care about this scenario? Notify them somehow?

Or just proceed? It is unstable after all, people should not just rely on the master branch.

Once this one is addressed, bugfix release can be tagged and #43, #109 can be closed.

**Comment by frederikbosch** [comment]
Thinking about it, I have another option to consider. Why not make a new branch: `3.x` which pulls from `nextrelease`. Then make the `3.x` branch the default branch on github. This ensures when people arrive on this project's page, they will see how to use `Money` the new way. My suggestion would be to split #137 and create an issue for only the README.md update. That one should be fixed in order to proceed.

Then we can release `3.0.0`. New development should be done in the `3.x` branch, where as the `master` and `nextrelease` branches will be retained (and locked/closed).

This way we will not break current installation while still being able to move forward.

**Comment by frederikbosch** [comment]
@sagikazarmark I just created my final set of PRs for 3.0.0. If we solve the negative amount issue in those PRs, I think it should be ready for shipment.

**Comment by sagikazarmark** [comment]
I think leaving master as is can be confusing. Nevertheless being 3.x the default, it's still master's role. So I think we should try to contact authors relying on master.

Relying on master is a bad idea anyway.

**Comment by frederikbosch** [comment]
@sagikazarmark What is stopping you from merging the 4 open PRs?

Do you have the ability to tag a new version? Or do we need Mathias for that?

**Comment by sagikazarmark** [comment]
Lack of time, sorry. :cry:

**Comment by sagikazarmark** [comment]
Development is happening on master branch now.

**Comment by frederikbosch** [comment]
:+1:
