### ISSUE TITLE
Method __toString not implemented for 'Money\Money'

### ISSUE THREAD

**Issue by mikemand** [moneyphp/money#184]
Would it be possible to implement? I noticed that between v1 and v3, you've added JSON support (thank you very much for that), but I still cannot just `echo` out a Money object.

The new `MoneyFormatter` is awesome, would it be possible to implement `__toString` to call it somehow?

**Comment by frederikbosch** [comment]
@mikemand What would you suggest as the outcome? Because I cannot see why you want this.

If you want to change Money into a human readable string, you will need a formatter mostly because of displaying a currency is different for anyone. So that leaves only displaying the amount. What would one benefit to do `(string) $money` instead of `$money->getAmount()`?

The only thing I can think of is that you are using some kind of Active Record pattern where is no such thing as a value object (at least not in the ones that I am aware of). But you still want the money object to be stored in the database. And `$record->orderTotal = $money` is troubling because it cannot be casted to a string? Something like that?

**Comment by sagikazarmark** [comment]
@mikemand in 3.0 we tried to **remove** responsibilities from the Money objects. We a few removed special construction logic. The reason why we introduced formatters is to support any kind of formatting logic.

Which do you think should be the default? We could have something like concatenation of amount and currency name...but I'm not sure about the use case.

**Comment by mikemand** [comment]
I was going to suggest just having `__toString` call the `MoneyFormatter` and return its output but now that I think about it, I don't think it would be feasible. It would assume way too much about the end user's setup, notably that they have set the `LC_MONETARY` locale correctly. And it would also let the Money object know about its Formatter, which is against the whole point of the Formatter in the first place.

My specific use case is to pull the amount (stored as an int - which lines up great with) and currency from the database through my DBAL (in this case, Eloquent's Active Record) via my Repository then display it for the user. However, I can just as easily use my Repository (or even a transformer/presenter of some sort) to build the display and output that instead.

Thank you for your time, and this wonderful package.

**Comment by ruudk** [comment]
The default `__toString` should not be called to present the Money to an end user or to store it in a database. That should be something special depending on your use case.

But it's super convenient for logging purposes. In my opinion, the `__toString` method should just format itself as `EUR 5.00` using this code:
```php
public function __toString() : string
{
    $formatter = new DecimalMoneyFormatter();
    return sprintf('%s %s', $this->currency->getCode(), $formatter->format($this));
}
```

Then when you write money objects to the log, they will be converted to `EUR 5.00` instead of `[object Money\Money]`.

This way, the Money objects just presents itself in a more usable form to the developer.

**Comment by frederikbosch** [comment]
> If you don't want to use the Formatter or ISOCurrencies I would also be fine with EUR 500 as output, as long as I know it. Or make it EUR:500 so that everybody will know it's not a regular representation of the value, but developers understand it's 500 EUR cents.

Suppose we would do that, and for logging purposes I can imagine it being justified, then the next question would be to implement `Money::fromString`, which would confuse many people, expecting to put `€ 5,00` in there.

**Comment by ruudk** [comment]
I fixed it by adding a custom Monolog LineFormatter :)

**Comment by armetiz** [comment]
I want to add a vote.
I agree that Money to `human readable string` is not a good idea, but Money to `developer readable string` is a good idea ;)

This is not a killer feature,
But when I'm adding assertion on business logic, I would be happy to be able to do something like that :

```php
$total = new Money(42000, new Currency('EUR'));

Assertion::true($total->isPositive(), sprintf('Total have to be positive, given: %s', $total));
```

Just a simple helper, but.. Useful on day-to-day.

Note:
* `fromString` is not a mandatory method when designing a `__toString`. 
* Because PHP `__toString` method could be a problem due to the lake of intention (human readable, technical readable, computer serialization..), use an explicit method ? ie: `toSystem`, `formatISO` ... ?

Regards.
