### ISSUE TITLE
Rounding of negative numbers is weird

### ISSUE THREAD

**Issue by davidomelettes** [moneyphp/money#185]
I'm exposing my mathematical ignorance here, but could someone explain to me how the calculator arrives at the following?

```php
$currency = new Currency('GBP');
$money = new Money(158243, $currency);
$percent = -5;
$multiplier = ((100 / (100 + $percentage)) * $percentage) / 100; // -0.052631578947368
$amount = $money->multiply($multiplier);
var_dump($amount->getAmount()); // -8327
```

To my eyes, here's the maths I expect to happen here:

`1582.43 * -0.052631578947368 = -83.285789474`

Which, when rounded to two decimal places using PHP_ROUND_HALF_UP should be:

`-83.29`

Getting `-83.27` instead just doesn't seem right to me, whatever the rounding mode is. Can anyone explain?

**Comment by sagikazarmark** [comment]
One problem I can see: this is what actually happens:
`158243 * -0.052631578947368`

There is no internal subunit conversion. Apart from that you described it correctly.

HALF_UP in this (and actually in every) case rounds in the higher number direction, which is (weird or not) towards the lower absolute value.

From my point of view this is the logical behavior.

**Comment by davidomelettes** [comment]
But it's not HALF_UP, it's PHP_ROUND_HALF_UP. Or at least, that's what it purports to be.

```$ php -r 'echo round(158243 * -0.052631578947368, 0, PHP_ROUND_HALF_DOWN);'
$ -8329
`

Even if it was rounding '-8328.578947368' in the other direction, should that not mean the expected result would be `-8328`? I'm still struggling to see how it arrives at `-8327`.

**Comment by sagikazarmark** [comment]
Well, there is something interesting going on here:

``` bash
$ php -r 'echo round(158243 * -0.052631578947368, 0, PHP_ROUND_HALF_UP);'
$ php -r 'echo round(158243 * -0.052631578947368, 0, PHP_ROUND_HALF_DOWN);'
```

Both returns `-8329` since there is probably no halfway here. I will check this issue, thanks for reporting.

**Comment by pamil** [comment]
@sagikazarmark it takes the `HALF_UP` and `HALF_DOWN` modes into account only if the fraction is exactly 0.5, nothing more, nothing less.

By the way, PHP's `round()` behaves incorrectly for these modes, as `HALF_UP` rounds away from zero instead of towards the positive infinity, the opposite for `HALF_DOWN`.

**Comment by frederikbosch** [comment]
@sagikazarmark @pamil @davidomelettes Sorry, I missed the debate. But as soon as I saw the bug being reported, I decided to reproduce it. Saw the current version contained mistakes and fixed it. I'd probably better have told directly that I was working on a fix.

Could you all three have a really really thorough look at the PR? The behaviour that is inside the `BcMathCalculator` and `GmpCalculator` need a very good review because both were behaving different than the `PhpCalculator` in the case of negative numbers.

**Comment by frederikbosch** [comment]
And pretty please: style fixes come last. The focus MUST be on the API and the behaviour inside the classes first.

Since the number of stars inside this package raised very quickly in the last months, I guess many people are already pulling the current beta package inside their projects. This means good reviews cannot wait any longer. I hope (and count on) your help to give a qualitative review.

**Comment by frederikbosch** [comment]
@davidomelettes Thank you very much for brining this up. There were no tests concerning negative numbers in the library. I added plenty today and yesterday, fixing more than one issue regarding negative numbers.

Also, two new rounding modes were added: `ROUND_HALF_POSITIVE_INFINITY` and `ROUND_HALF_NEGATIVE_INFINITY`. This should fix the issue brought up by @pamil. I would be really grateful if both of you could help us by reviewing PR #186. This is quite complicated and needs more than two eyes (being me and @sagikazarmark).

**Comment by davidomelettes** [comment]
I've been keeping an eye on your PR, and have been unable to find any fault in your work.

Am I to understand that the HALF_UP rounding mode will now be equivalent to PHP_ROUND_HALF_UP? That is, it will round away from zero?

**Comment by frederikbosch** [comment]
@davidomelettes [`HALF_UP` was always an equivalent of `PHP_ROUND_HALF_UP`](https://github.com/moneyphp/money/blob/1.x/lib/Money/Money.php#L15). We decided not to change that, but rather add a new `ROUND_HALF_POSITIVE_INFINITY` rounding mode for rounding towards zero.

**Comment by davidomelettes** [comment]
ROUND_HALF_POSITIVE_INFINITY rounds towards zero?

I agree, documentation will be key. ;)

**Comment by frederikbosch** [comment]
@davidomelettes Towards zero for negative numbers. `ROUND_HALF_POSITIVE_INFINITY` rounds towards positive infinity. So 1.5 becomes 2 and -1.5 becomes -1. This is different from `ROUND_HALF_UP`, where a -1.5 becomes -2.

**Comment by frederikbosch** [comment]
@davidomelettes But, if you have a suggestion for a better name, please bring it up :)

**Comment by davidomelettes** [comment]
Makes perfect sense, with the right context. I agree with the naming.

**Comment by pamil** [comment]
@frederikbosch naming sounds good, some documentation for these rounding modes and it'll be all right :tada:

**Comment by frederikbosch** [comment]
Alrighty then. When @sagikazarmark gives his confirmation, we are ready to merge.

**Comment by sagikazarmark** [comment]
Thanks for your work on this @frederikbosch

**Comment by frederikbosch** [comment]
My pleasure!
