### ISSUE TITLE
Conversion back and forth

### ISSUE THREAD

**Issue by fedeisas** [moneyphp/money#189]
Hi! I'm having some issues converting money back and forth. Is that operation supposed to be idempotent?

Example:

```php
$ratio = 14.834670;
$inverseRatio = round(floatval(1/$ratio), 6);

$USDARSpair = \Money\CurrencyPair::createFromISO('USD/ARS ' . $ratio);
$ARSUSDpair = \Money\CurrencyPair::createFromISO('ARS/USD ' . $inverseRatio);

$numberFormatter = new \NumberFormatter('en_US', \NumberFormatter::CURRENCY);
$formatter = new \Money\Formatter\IntlMoneyFormatter($numberFormatter);
$money = new \Money\Money(4250, new \Money\Currency('ARS'));

var_dump($formatter->format($money));
var_dump($formatter->format($ARSUSDpair->convert($money)));
var_dump($formatter->format($USDARSpair->convert($ARSUSDpair->convert($money))));

string 'ARS42.50' (length=8)
string '$2.86' (length=5)
string 'ARS42.43' (length=8)
```

I know maybe the problem is in how I'm calculating the `$inverseRatio`.

Thanks!

**Comment by fedeisas** [comment]
I think it's because when you can `Money::convert` it rounds the value to cents. Maybe rounding should be done upon formatting?

**Comment by sagikazarmark** [comment]
``` bash
$ php -r 'echo round(floatval(1/14.834670), 6) * 14.834670;'
```

This should end up in exactly one and it does not. I hardly think that this is a CurrencyPair issue, but the result of the rounding. In order to preserve consistency (and hence the immutability) we cannot do rounding upon a specific action. After each one, the rounding is done. But as you can see, this is the mistake of "your"/php's rounding, not Money's one.

**Comment by frederikbosch** [comment]
@sagikazarmark is right.

```
4250×0.067409656 = 286.491038
4243×0.067409656 = 286.019170408
```

Both result in an amount of `286` when rounding. You will need `PreciseMoney`, which will be realized in `3.1.0`, in order to have a money value object with decimals.

However, you could change the value object by changing the fraction of the amount to 5.

```php
$ratio = '14.834670';
$inverseRatio = '0.067409656';

$pair = CurrencyPair::createFromISO('USD/ARS ' . $ratio);
$inversePair = CurrencyPair::createFromISO('ARS/USD ' . $inverseRatio);

$moneyUsd = new Money(286000, new Currency('USD'));
$moneyArs = new Money(4243000, new Currency('ARS'));

$this->assertEquals(4242716, $pair->convert($moneyUsd)->getAmount());
$this->assertEquals(286019, $inversePair->convert($moneyArs)->getAmount());
```

But that will have consequences for your whole application.
