### ISSUE TITLE
Numberformatter returning wrong formatted amount

### ISSUE THREAD

**Issue by bramstroker** [moneyphp/money#221]
Following you documentation we should construct new `Money` objects using the smallest unit (eg. cents). This means `new Money(100, 'EUR')` is the same as 1 Euro.

When using the IntlMoneyFormatter which uses NumberFormatter I get the wrong amount outputted.

Output:
€ 100

Expected:
€ 1

The `IntlMoneyFormatterSpec` test also is wrong imo.

**Comment by sagikazarmark** [comment]
Can you please try setting the fraction digit attribute of the number formatter?

https://github.com/moneyphp/money/blob/master/tests/Formatter/IntlMoneyFormatterTest.php#L24

**Comment by bramstroker** [comment]
@sagikazarmark 
I get a "correct" value when using fraction digits 2.

€ 1,00

But this is not the same behaviour as using the NumberFormatter without the Money object. i.e.
Fractional digits should only affect the position of dots and comma's and decimal positions, but never affect the base value.

    $numberFormat = new NumberFormatter('nl_NL', NumberFormatter::CURRENCY);
    $numberFormat->setAttribute(NumberFormatter::FRACTION_DIGITS, 2);
    echo $numberFormat->formatCurrency(500, 'EUR') . PHP_EOL;
    //Outputs € 500,00

    $numberFormat->setAttribute(NumberFormatter::FRACTION_DIGITS, 0);
    echo $numberFormat->formatCurrency(500, 'EUR') . PHP_EOL;
    //Outputs € 500

**Comment by sagikazarmark** [comment]
Fraction digit in our case is the same as the subunit. Unfortunately we haven't found a better way to use the core NumberFormatter. Subunit is not part of the money object, that's why you must configure it in the formatter (in our case, in the number formatter).

If you have a better idea, please give us a hint, but I think @frederikbosch investigate the possibilities quite well.

**Comment by bramstroker** [comment]
@sagikazarmark 
Thanks for the explanation. I now understand why you choose to do it like this.
You mean by subunits the amount of decimals which needs to be substracted to get to the "normal" value? I.e.  500 / 100 = 5
Maybe it would be a good idea to add that "factor" to the constructor of the `IntlMoneyFormatter`, That way it would not alter the core NumberFormatter behaviour and the implementation can be much simpler imo by just dividing the amount by the specified factor instead of all the string padding what happens now,

**Comment by sagikazarmark** [comment]
AFAIK we had it in the constructor once, no idea, why we removed. However (looking at the formatter code) we not just rely on the NumberFormatter instance, but actually use the attribute in the code. This would make it impossible to format money to have fraction digits.

For example:

``` php
$money = new Money(500, new Currency('EUR')); // this means 500 EUR, no subunits
$numberFormat->setAttribute(NumberFormatter::FRACTION_DIGITS, 2);
$formatter->format($money);
//Outputs € 5,00 not € 500,00
```

@frederikbosch can you give us an input here?

**Comment by bramstroker** [comment]
@sagikazarmark 
It feels not really good to me to, because:

- You use FRACTION_DIGITS as a "hack" to get the amount of zero's for the subunits
- The user must alter the numberFormatter state each time you format a value, which is an implementation detail and not visible by looking at the public API

Maybe you can alternatively alter the interface definition to make it possible to pass the "factor" there.

    function format(Money $money, $factor = 2)

**Comment by sagikazarmark** [comment]
The factor is highly dependent on use case (eg. currencies without subunits or application does not care about them), but probably that's the most common configuration of the money object. So either add it to the interface (increases coupling, which is not good IMO), add a new interface (FactorAwareFormatter), or rather make it a constructor argument.

**Comment by frederikbosch** [comment]
@bramstroker @sagikazarmark There are a few things at play here. I will walk them through step by step.

1. Money is unaware of the number of subunits. While that might be two digits for the majority of the Western currencies, this is [not always the case](http://www.localeplanet.com/icu/currency.html). There are currencies with 0, 2 or 3 as default fraction digit.

2. This means that fractions digits belongs to presentation: parsing and formatting a `Money` object. While creating our formatters, we created a `IntlMoneyFormatter` that had the [fraction digits and locale](https://github.com/moneyphp/money/pull/123/files) in its constructor.

3. But then we found out that the `\NumberFormatter` from the `intl` extension [behaves differently per system](https://github.com/moneyphp/money/pull/148). We could not find out how to reset the behaviour as such that we had control over it unless we were using a [`pattern`](http://php.net/manual/en/numberformatter.setpattern.php). That left us with two options: `IntlMoneyFormatter` where the user injects its own `\NumberFormatter`, or secondly `PatternizedMoneyFormatter` where the user injects its own `pattern` that would be used to format a currency. Since the former gives the user most control, I choose for that option.

4. Then the string padding. Since version 3.0 we are supporting integer higher than `PHP_INT_MAX` through `BCMath` and `GMP` we cannot use regular PHP divisions anymore because that might lead to over/underflows. The internal amount is a string, not an integer a any more. So `amount / 100` is unfortunately not possible. I got around with it by using string padding.

Finally, the above does not mean you, as a client user of the library, are not able to implement different behaviours. You can simply implement your own implementation of `MoneyFormatter` by creating a completely new class or you can decorate the `IntlMoneyFormatter` to your likes. Please see the example below.

```php
<?php
namespace My;

use Money\Formatter\IntlMoneyFormatter as BaseIntlMoneyFormatter;
use Money\MoneyFormatter;

final class IntlMoneyFormatter implements MoneyFormatter {
  private $delegatedFormatter;

  public function __construction ($fractionDigits) {
    $numberFormatter = new \NumberFormatter();
    $numberFormatter->setAttribute(\NumberFormatter::FRACTION_DIGITS, $fractionDigits);
    /* set some more attributes on the number formatter here */
    $this->delegatedFormatter = new BaseIntlMoneyFormatter($numberFormatter);
  }

  public function format(Money $money) {
    return $this->delegatedFormatter->format($money);
  }
}
```

Hopefully this makes sense and helps you moving on with formatting your `Money` object.

**Comment by sagikazarmark** [comment]
Reopening this as I think it is not solved yet. While I understand the points above, I still think we misuse the `NumberFormatter` as @bramstroker pointed. See this case:


``` php
$money = new Money(500, new Currency('EUR')); // this means 500 EUR, no subunits
$numberFormat->setAttribute(NumberFormatter::FRACTION_DIGITS, 2);
$formatter->format($money);
//Outputs € 5,00 not € 500,00
```

With other words: we are not able to control fraction digits anymore, but only subunits.

**Comment by frederikbosch** [comment]
@sagikazarmark Now I get it. I will issue a PR.

**Comment by frederikbosch** [comment]
See #223.
