### ISSUE TITLE
GmpCalculator multiply:  gmp_init() error when fractional part with leading 0

### ISSUE THREAD

**Issue by Michael-vb** [moneyphp/money#286]
```PHP
$phpCalculator = new \Money\Calculator\PhpCalculator;
$gmpCalculator = new \Money\Calculator\GmpCalculator;
$bcCalculator = new \Money\Calculator\BcMathCalculator;
echo $phpCalculator->multiply('100', 0.029) . "\n"; // 2.9
echo $gmpCalculator->multiply('100', 0.029) . "\n"; // .0 gmp_init(): Unable to convert variable to GMP - string is not an integer
echo $bcCalculator->multiply('100', 0.029) . "\n"; // 2.900
```

**Comment by sagikazarmark** [comment]
I think a similar issue has already be raised here: #278

Just for curiousity: what made you using the calculator directly? As far as I know it works well with the money object.

@frederikbosch since this issue keeps coming back, maybe we should do something about it. Put some lines in the docs, even throw an exception somewhere?

**Comment by Michael-vb** [comment]
@sagikazarmark no it didn't work with the money object too. But by default money object uses bcmath and this error occurs when bcmath is not installed. e.g.:

```PHP
Money::registerCalculator(\Money\Calculator\GmpCalculator::class);
(new Money(1000, new Currency('USD')))->multiply(0.029);
```
will throw the error

**Comment by frederikbosch** [comment]
@Michael-vb This has been fixed in the latest master.

**Comment by frederikbosch** [comment]
Thanks for reporting.

**Comment by Michael-vb** [comment]
@frederikbosch thank you! I've seen. Just answered the previous question
