### ISSUE TITLE
No support for cache TTLs in SwapExchange

### ISSUE THREAD

**Issue by MichaelGooden** [moneyphp/money#345]
`Swap\Swap` has support for caching, however cache TTLs must be set by the implementing library (us). `SwapExchange` has no such support.

I propose adding support via an optional constructor parameter to `SwapExchange` that allows setting a cache TTL, and then sending that as an option to the `Swap` library when getting rates. If you are happy with this idea, I will submit a PR.

**Comment by sagikazarmark** [comment]
Hm, you could add your options here: https://github.com/florianv/exchanger/blob/master/src/ExchangeRateQueryBuilder.php#L19

**Comment by MichaelGooden** [comment]
How, that is an internal object that is created dynamically when you request an exchange.

Trust me, there is no way to do this without changing source files or making ugly hacks.

**Comment by sagikazarmark** [comment]
Ah, sorry, overlooked a class name, they are so similar. :smile: 

Sure thing then, but I would rather create an optional options array and pass it as is to the underlying object. Is that what you are suggesting?

**Comment by frederikbosch** [comment]
@MichaelGooden Isn't this a reason to create a new object? CachedSwapExchange. Which should be in your own namespace?

**Comment by MichaelGooden** [comment]
I could of course easily do that, but I feel that caching support for something like this that is accessing public web services would be used often enough to validate inclusion in the base project?

**Comment by frederikbosch** [comment]
@sagikazarmark Maybe it does indeed. Since I don't do a lot with exchange and caching, could you take this one? :)

**Comment by sagikazarmark** [comment]
I usually do caching on the HTTP Client level, but if Swap has support for it on it's own level, I don't see a problem supporting it.

Personally I think supporting Swap's config options would be a better way to go. There are no default config support in Swap, so the options has to be passed when the actual quote-ing happens. For that a simple, optional options array would be perfect in our SwapExchange. That way caching is implicitly supported.

If you want to open a PR @MichaelGooden, go ahead with the above in mind, otherwise I will pick it up as soon as my time allows.

**Comment by frederikbosch** [comment]
Reopen if still necessary
