### ISSUE TITLE
MIssing currency `nameFor($currency)` method?

### ISSUE THREAD

**Issue by lukeholder** [moneyphp/money#379]
Not sure if I am missing something, but how can I get the name for a currency? Should there be a 

`nameFor(Currency $currency)` method in the `ISOCurrencies` class?

Just like there is for `numericCodeFor`: https://github.com/moneyphp/money/blob/master/src/Currencies/ISOCurrencies.php#L43-L59

Thanks.

**Comment by frederikbosch** [comment]
That is not possible at this moment. You could create something like the following.

```php
namespace MyNamespace;

final class NamedISOCurrencies implements \IteratorAggregate, \ArrayAccess {
 // read the currencies php file and implement the interface methods
}
```

Then you can do the following.

```php
$currencies = new NamedISOCurrencies();
foreach ($currencies as $code => $name) {}
$dollar = $currencies['USD'];
```

However, it is something that belongs in your own namespce. We do not want to have it in this library, because it opens up a world that we do not want to get into. Next thing request would be internationalized names or to distribute even more properties of currencies. This library is to help with domain issues regarding money and amounts. This is not a currency repository. Hope you understand.

**Comment by pumi2527** [comment]
379

**Comment by pumi2527** [comment]
#379

**Comment by frederikbosch** [comment]
?
