### ISSUE TITLE
Money sum

### ISSUE THREAD

**Issue by melokki** [moneyphp/money#387]
Hello everyone

I want to make a sum for the amount of more than 2 Money objects. 
I thought I can make this using the `add` function, until I read the documentation and I've seen that `add` function returns a string not a Money object.

Do you have any idea how I could make a sum for more than 2 Money objects?

**Comment by sagikazarmark** [comment]
I am pretty sure that [add](https://github.com/moneyphp/money/blob/master/src/Money.php#L229) returns a Money object.

For now you could go with the following code:

```
/** $addends Money[] */
$addends = [];

$money = Money::EUR(1);

foreach ($addends as $addend) {
    $money = $money->add($addend);
}
```

I can see a lot of potential improvements on this front: accept a variadic argument list, return type, etc. Version 4 will likely come with PHP 7.2 as the minimum version.

**Comment by frederikbosch** [comment]
@sagikazarmark I am also interested in the sum function.

**Comment by sagikazarmark** [comment]
Not sure if it's necessary. With variadic we can do something like this

``` php
public function add(...Money $money)
```

then use it like

``` php
$money = $money->add($m1, $m2, $m3, ...);
```

**Comment by frederikbosch** [comment]
@sagikazarmark Cool. That's a good idea. Maybe we should go for version 4 and have PHP 7.1 as next minimal version. I do not think 7.2 has any syntax changes that we will benefit from specifically, so 7.1 would be fine.

**Comment by melokki** [comment]
Yes, I've saw that the add function returns a Money object in the code after I wrote this message, but when I came the delete the message it was too late, the replies were already here.

Thank you for your answer @sagikazarmark It helped me to solve the problem :)

**Comment by sagikazarmark** [comment]
Further thinking about this: we can implement this functionality now using `func_get_args`.

**Comment by frederikbosch** [comment]
@sagikazarmark I rather see an additional method. Cannot explain why though.

**Comment by sagikazarmark** [comment]
I don't understand why.

``` php
$money->add($m);
$money->add($m, $m, $m);
```

similarly:

```
1 + 2
1 + 2 + 3
```

**Comment by gmponos** [comment]
> Further thinking about this: we can implement this functionality now using func_get_args.

```
$money->add($m);
$money->add($m, $m, $m);
```

@sagikazarmark can you accomplish this without breaking BC?

**Comment by sagikazarmark** [comment]
Why would it be dirty? As long as PHP 5.6 is not a hard requirement we can emulate a variadic using `func_get_args`. Maybe it's not nice to the eye, but it works, is forward compatible and a widely accepted solution to this particular problem (lack of variadic).

**Comment by frederikbosch** [comment]
@sagikazarmark Thinking it through, I agree that `add(...Money)` would be an enhancement to the library. I'd say we go for a new major version with at least PHP 5.6 support and add this to the list of ideas, because we can then use `...Money`. But if you want to implement it in the current lib, I have nothing really against it.

I do think, that `...Money` would have be the second argument. There should be at least one amount to be added.

```php
function add(Money $addend, ...Money $extraAdded){}
```

I would also like to note that when I saw this issue, I first thought it would mean a static constructor that accepts an array of amounts.

```php
$money = Money::sum([Money::EUR(10), Money::EUR(5)]);
```

How about that? That is more than just adding up the amounts, because we need to check if the array is empty. I actually would like to see this feature, because it would help me in many cases. Something like this.

```php
public static function sum(array $amounts, Currency $currencyIfEmptyAmounts = null): Money {
  if (empty($amounts) && $currencyIfEmptyAmounts === null) {
     throw new SomeException;
  }

  if (empty($amounts)) {
     return new Money(0, $currencyIfEmptyAmounts);
  }

  return array_unshift($amounts)->add($amounts);
}

**Comment by gmponos** [comment]
Sorry I thought that Money object extends somekind of an Interface.

Since it does not you can remove the argument from function `public function add(Money $addend)` and have it as `public function add()` then use func_get_args and nothing will break since the class is also final.

**Comment by sagikazarmark** [comment]
@frederikbosch Well, I think both the following could work:

`function add(Money $addend, ...Money $extraAdded){}`

`function add(...Money $addends){}`

I don't see a reason why we should validate if there is a first argument. In fact, if we support variadic I could imagine that someone may want to expand an array of money objects and just pass that to money::add (eg. shopping cart amendments). That array could even be empty (no amendments). In that case the user would have to introduce a check instead of just calling add. So I would say there is no need to check if there is a first addend.

About sum: why not just use add?

`Money::EUR(0)->add(....)`

The currencyIfEmpty sounds a bit leaky and error prone to me. User should be explicit about the currency here. Also, from a UX point of view array is somewhat less convenient IMO (at least compared to variadic).

For me the variadic add sounds like the cleanest possible solution.

@gmponos exactly.

**Comment by sagikazarmark** [comment]
Since we dropped PHP 5.5 support, we can implement this functionality using variadic.

**Comment by frederikbosch** [comment]
Good idea! We should implement it in a consistent manner and add it for all arithmetic operations.

**Comment by sagikazarmark** [comment]
Hm, which operations exactly?

Add and subtract probably makes sense, but not sure if others do.

**Comment by bendavies** [comment]
I'm just using this in my project:

```php
function sum(Money ...$collection): Money
{
    $result = array_pop($collection);
    foreach ($collection as $value) {
        $result = $result->add($value);
    }

    return $result;
}
```

**Comment by sagikazarmark** [comment]
Thanks for sharing. My plan is to change the add function to be variadic and accept more than one arguments.

**Comment by sagikazarmark** [comment]
@bendavies see #456

**Comment by Banandrew** [comment]
@sagikazarmark Hello, could you please confirm that variadic arguments work? I’ve just tried the example from the documentation in isolation, it only adds the first argument and ignores the rest:
```PHP
$value1 = Money::EUR(800);                // €8.00
$value2 = Money::EUR(500);                // €5.00
$value3 = Money::EUR(600);                // €6.00

$result = $value1->add($value2, $value3); // €13.00, because $value3 is ignored.
```

**Comment by frederikbosch** [comment]
@Banandrew It’s not released yet. Only available in master now.

**Comment by Banandrew** [comment]
@frederikbosch Thank you, the reason why I got confused is because the documentation on `moneyphp.org` resolves to the `latest` version by default — perhaps, it would be better to use `stable` instead.

**Comment by frederikbosch** [comment]
Yeah, you’re right. We will have a look into that.

**Comment by sagikazarmark** [comment]
Stable is now the default version on RTD.
