### ISSUE TITLE
BCMath vs GMP

### ISSUE THREAD

**Issue by alvinchevolleaux** [moneyphp/money#407]
I would suggest considering changing the driver loading priority to use GMP instead of BCMath. It should be more performant in most cases so I don't see why BCMath is used over GMP by default if both extensions are loaded.

**Comment by sagikazarmark** [comment]
Personally I'm not against that change, normally users should not be able to tell the difference, if they do, that's a leak in the abstraction.

What do you think @frederikbosch ?

**Comment by frederikbosch** [comment]
@alvinchevolleaux It is indeed more performant. However, since it does not support rounding (no decimals numbers), I was reserved towards my implementation of it. Compare the two calculator classes and see the difference in required code to achieve multiplying and division. The least thing I could do was prioritizing BCMath over GMP.

**Comment by alvinchevolleaux** [comment]
Okay fair enough. Maybe if I have time one day I could try a PR myself adding this functionality to the calculator class of GMP.

**Comment by frederikbosch** [comment]
@alvinchevolleaux It is already added. GMP is only not the default calculator because I found that too risky.
