### ISSUE TITLE
Conversion result is always 0 when subunit difference is large enough

### ISSUE THREAD

**Issue by dmitry027** [moneyphp/money#425]
I'm trying to operate with custom "Ether" cryptocurrency using the library, but conversion to/from other currencies doesn't work as expected: the result is always 0. The problem is that "Ether" subunit value is 18.

Since in `Money\Converter::convert()` we do
```php
$ratio = $ratio / pow(10, $subunitDifference);
$counterValue = $money->multiply($ratio, $roundingMode);
```
the result will always be 0 if `$ratio` is too low or `$subunitDifference` is too large, because first argument of `Money\Money::multiply()` will be rounded to 8 decimal places inside.

**Comment by frederikbosch** [comment]
I kind of get your problem. Can you however emphasize with an example?

**Comment by dmitry027** [comment]
```php
use Money\Converter;
use Money\Currencies;
use Money\Currencies\AggregateCurrencies;
use Money\Currencies\ISOCurrencies;
use Money\Currency;
use Money\Exception\UnknownCurrencyException;
use Money\Exchange\FixedExchange;
use Money\Money;

final class EthereumCurrencies implements Currencies
{
    const CODE = 'ETH';

    public function contains(Currency $currency)
    {
        return self::CODE === $currency->getCode();
    }

    public function subunitFor(Currency $currency)
    {
        if ($currency->getCode() !== self::CODE) {
            throw new UnknownCurrencyException(
                $currency->getCode() . ' is not ethereum and is not supported by this currency repository'
            );
        }

        return 18;
    }

    public function getIterator()
    {
        return new \ArrayIterator([new Currency(self::CODE)]);
    }
}

$currencies = new AggregateCurrencies([
    new EthereumCurrencies(),
    new ISOCurrencies(),
]);

$exchange = new FixedExchange([
    'ETH' => [
        'USD' => 330.84,
    ],
]);

$converter = new Converter($currencies, $exchange);

$eth = Money::ETH('1');
$usd = $converter->convert($eth, new Currency('USD'));
echo $usd->getAmount() . "\n";         // expected: 0, actual: 0

$eth = Money::ETH('10');
$usd = $converter->convert($eth, new Currency('USD'));
echo $usd->getAmount() . "\n";         // expected: 0, actual: 0

$eth = Money::ETH('100000000000000000');  // 10^17
$usd = $converter->convert($eth, new Currency('USD'));
echo $usd->getAmount() . "\n";         // expected: 3308, actual: 0

$eth = Money::ETH('1000000000000000000'); // 10^18
$usd = $converter->convert($eth, new Currency('USD'));
echo $usd->getAmount() . "\n";         // expected: 33084, actual: 0
```

**Comment by frederikbosch** [comment]
@sagikazarmark This is a harder problem. The problem is [on this line](https://github.com/moneyphp/money/blob/master/src/Converter.php#L48). That results in a float. Then, in the next line, `$money->multiply` is called. Because a floating point is given as multiplier, it is [converted to string first](https://github.com/moneyphp/money/blob/master/src/Money.php#L310). So, `Number::fromFloat` is called, which on its turn calls `sprintf` to convert the float to a real number. And `sprintf` is not aware of big integers.

So, this problem has two possible solutions. One: fromFloat should return big integer aware results. Two: we change [the calculation that results in a float](https://github.com/moneyphp/money/blob/master/src/Converter.php#L48) instead of string.

**Comment by frederikbosch** [comment]
Three. We add a calculation method to Money in order to use a `Calculator` for the calculation.

**Comment by frederikbosch** [comment]
I think the `pow` calculation can be removed, and replaced by a simple string manipulations. I'll try that first.
