### ISSUE TITLE
Best way to get integer representation of Money now that getAmout() returns string

### ISSUE THREAD

**Issue by enekochan** [moneyphp/money#453]
I have an app that currently relies on `moneyphp/money` version v1.3.0. I want to upgrade it to ^3.1 and found some compatibility issues. For example `Currency::getName` is now `Currency::getCode`. No problem with that, just change those calls.

But now that the amount is stored internally as an `string` and that `getAmount()` also returns an `string` and I have lots of places were I get errors because I use the returned int value to do some things, like adding/dividing it with something, comparing it with 0 (`if ($money->getAmount() === 0)` or `if ($money->getAmount() > 0)`) or returning it in a JSON as an `int`.

What would be now the best approach to get the int representation in the new version 3? Just use intval()? Or is there something in the library that can be used for that? I've been looking and couldn't find any.

Thanks.

**Comment by sagikazarmark** [comment]
For one, you could check the changelog to see all changes since 1.x, there are quite a few breaking changes, but that should be okay as they are released under a new minor version.

We decided to store the amount internally as string because there are many cases when we have to work with string representations: formatting, parsing, arbitrary precision libs(bcmath, gmp).

If you know you have only values within the integer limit of your platform, you should be safe casting the amount to integer. (Note that in case the integer limit overflows the resulting value will be of type float).

Alternatively you can use builtin comparison and mathematical functions.

See the documentation for details: http://moneyphp.org

**Comment by enekochan** [comment]
I think I'll go with using the builtin comparison and mathematical functions most of the times and rework my API client so it works with string amounts. Thank you.

**Comment by sagikazarmark** [comment]
Whatever is best for you! Good luck!
