### ISSUE TITLE
Float to string casting provides errors on some locales

### ISSUE THREAD

**Issue by chekalskiy** [moneyphp/money#455]
```php
$full_summ = new Money(1000000, new Currency('RUB'));
$vat_summ = $full_summ->divide(1.18);

echo 'Should be: ' . round(10000/1.18, 2);
echo "<br>\n";
echo 'We have: '. $vat_summ->getAmount()/100;
```

Gives us:
```
Should be: 8474,58
We have: 8474,57
```

After debugging I found that it's because of `divide($amount, $divisor)` in `PhpCalculator.php` — there we have `return (string) $result` — on some locales (e.g. ru_RU.UTF8) it creates 847457,627 instead of 847457.627 and after that that part after the comma are gone in further operations.

**Comment by sstok** [comment]
Don't use float for monetary values, use bcmath or gmp with a correct precision 👍

The problem with float is that it's not precise enough for money values and easily leads to rounding problems. Just Google "money as float" 😅 and you will see everyone will tell you it's not good idea.

Sorry if my reply sounds a bit harsh. I am under the weather.. and can't think of a proper way to comminate this.

**Comment by sagikazarmark** [comment]
Thanks for your answer @sstok , but I'm afraid it's not relevant in this case.

Although you are right about not using float for monetary values, during some internal calculations it's inevitable that some results will be float values before converting them back to integer. The problem here is that based on the locale PHP casts float values to string with different decimal separators.

Although heavily argued, but arbitrary precision libraries (especially when used in an environment where you have no, or limited control of the input, like all web applications written in PHP) can carry some security issues, so it may not fit everyone. (Read earlier issues and discussions)

@chekalskiy thanks for opening this issue, I will investigate it as soon as possible.

**Comment by sagikazarmark** [comment]
Tagged 3.1.2
