### ISSUE TITLE
Function to get least / highest from iterable of Money's

### ISSUE THREAD

**Issue by willemstuursma** [moneyphp/money#473]
We need a method or function to get the lowest or highest Money of an iterable of `Money`s. 

I was wondering if you have any suggestions on how to put this in the library and then I can provide a PR. 

Looking for something like:

`$money = Lowest(...$monies);`.

**Comment by sagikazarmark** [comment]
Money already has a compare method which follows the "standard" compare interface (-1, 0, 1).

Using that you write a simple minimum and/or maximum search as you would do with any other values.

All money methods are safe to use in terms of currency and other validity checks, meaning trying to compare values with different currencies results in an exception.

Note that creating a "zero" money value is not easy at all, because you have to know the target currency. This means you always need at least one money object in the input.

My first idea is to implement them as static functions in the Money class:

- `Money::min`
- `Money::max`
- `Money::avg`
- etc

@frederikbosch WDYT?

**Comment by willemstuursma** [comment]
This is our current implementation, for reference:

```php
function least(Money $first_item, Money ...$monies): Money
{
    $least = $first_item;
    foreach ($monies as $money) {
        if ($money->lessThan($least)) {
            $least = $money;
        }
    }

    return $least;
}

**Comment by frederikbosch** [comment]
I would love to have those static methods, for the same reason as we discussed with `sum`. The sum solution is OK, but as you already notice here, creating zero can difficult. I do think it is the best solution though. It is also compatible with the above example provided by @willemstuursma.

@sagikazarmark My/our initial conclusion in the `sum` PR was that an `iterable` cannot be unpacked. That is incorrect. See [argument unpacking via](http://php.net/manual/en/migration56.new-features.php) in the PHP doc.

So this example works.
```php
function x() {
  yield Money::EUR(1);
  yield Money::EUR(2);
}

$list = x();
Money::least(...$list); //Money::EUR(1)
```

which would make the static methods very powerful.

**Comment by sagikazarmark** [comment]
Nice, that would indeed make things easier. Also, the at-least-one-element problem can easily resolved by throwing an exception when the array resulting from the variadic has zero elements. But in that case you still have to make sure that your iterable contains at least one element or catch the exception and handle the fallback, but that's not that nice.

**Comment by frederikbosch** [comment]
@sagikazarmark Look at the code of @willemstuursma. He added a required first argument as `$first_item`. I think that is a very nice solution that requires the caller of the method to make sure the iterable has at least one argument. If the caller is not sure the collection contains one element, a zero amount has to be prepended to the call.

```php
public static function least(Money $first_item, Money ...$monies): Money {}

Money::least(...$list); // this caller knows really sure there is one argument
Money::least(Money::EUR(0), ...$list); // the caller does not know it for sure and adds a zero element
```

See also [this example](https://3v4l.org/ih4dA).

**Comment by frederikbosch** [comment]
So we don't have to check if the iterable is empty or not, that happens outside our scope.

**Comment by sagikazarmark** [comment]
Looking from a defensive perspective you can never be sure that there is at least one element. Think about a shopping cart: it can be empty or has items in it. Of course you can branch based on the cart item count, but that's again not very nice IMO.

**Comment by frederikbosch** [comment]
I don't understand that. Do you think the `$first_item` is nice, or not nice? In my opinion there are three options.

1. Require a `$first_item` as suggest by @willemstuursma.
2. Only the variadic argument and throw an exception if the list is empty.
3. Supply a `Currency` to be used to return zero if the list is empty.

**Comment by sagikazarmark** [comment]
> Of course you can branch based on the cart item count, but that's again not very nice IMO.

This is the problematic thing. Consider the following:

```php
$prices = $cart->getPriceIterator();
$sum = Money::sum($prices);
```

If you code in a defensive way, you have to put a zero value there because the iterator might be empty.

That would make every single usage of sum look like this:

```php
$prices = $cart->getPriceIterator();
$sum = Money::sum(Money::EUR(0), $prices);
```

In an earlier comment I think I already explained, that the currency here is probably a leak in your code. At this point you probably shouldn't know about it.

So I guess there is no nice solution using the aggregation functions, the implementation can work both ways, the problem remains the same.

**Comment by frederikbosch** [comment]
I don't agree, multiple reasons. First the example is wrong, because `$prices` is not unpacked, but I guess that was because you typed it fast.

> If you code in a defensive way, you have to put a zero value there because the iterator might be empty.

Not necessarily. As you can see in [this example](https://3v4l.org/ih4dA), PHP 7.0+ throw exceptions (ArgumentCountError and TypeError) when `$first_item` is not there. You can catch those and handle them. Only in PHP5.6 the result is an error. Or you decide to prepend the zero amount.

> In an earlier comment I think I already explained, that the currency here is probably a leak in your code. At this point you probably shouldn't know about it.

I don't agree. Take the cart example: if it is empty you are very likely to display the amount of zero somewhere. That is a result of a sum. So you must know the currency at that point. Actually, in all my applications using `Money` this is true. I see it as a domain requirement to know the currency before generating a sum.

**Comment by frederikbosch** [comment]
@sagikazarmark Shall I prepare the PR for this one? And then continue discussing it there?

**Comment by sagikazarmark** [comment]
Yeah, it looks like it's hard for me to imagine the actual usage, so would be nice to see it in form of tests and implementation.

**Comment by frederikbosch** [comment]
PR is there. Maybe you can both have a look.
