### ISSUE TITLE
Please keep floating point two after dividing by 100

### ISSUE THREAD

**Issue by wujunze** [moneyphp/money#487]
Please keep floating point two after dividing by 100

example:
```
        $price =  Money::CNY(2069)->divide(100,Money::ROUND_UP);
        echo $price->getAmount(); 
```
result
```
21
```
I hope so
```
20.69
```

Please tell me how to do it thank you

**Comment by sagikazarmark** [comment]
I'm not entirely sure what you are trying to do. Money stores amounts in integers internally (technically integers in strings). It also takes subunits into account, so when you write `Money::CNY(2069)` internally it is stored as `2069`, but it really means (for example when you try to format the money) is `20.69`.

If you divide that with 100 it will become `20.69` internally, which really means `0.2069`. Since this currency only handles values until 0.XX, the rest will be rounded.

Amount will only be an integer. If you want to format the money, use a MoneyFormatter, or keep in mind currency's subunit.

Hope this helps. I recommend you reading the documentation, these concepts are discussed there in details. If you are missing something from there, feel free to open another issue.

**Comment by wujunze** [comment]
I see  Thanks for you  @sagikazarmark
