### ISSUE TITLE
IDR minorUnit update

### ISSUE THREAD

**Issue by dmachehin** [moneyphp/money#515]
resources/currency.php for IDR has minorUnit=2 it's wrong, it's have minorUnit=0

**Comment by gmponos** [comment]
Hello there,

Most probably you are referring to the ISOCurrencies class. The Currencies of this class are fetched from this [API](https://www.currency-iso.org/dam/downloads/lists/list_one.xml). So the official ISO declares that IDR has decimals and [this](https://github.com/moneyphp/iso-currencies/blob/master/bin/fetch-update.php) is the file that updates the ISOCurrencies. There might be other lists that point that IDR does not have decimals, not sure. I think I have run into some of them.

From my experience as I work at a company that handles money everyday and believe me this is a very common mistake. IDR officially has 2 decimals but due to inflation (not sure if inflation is the correct word) IDR is an underestimated currency. People that are using IDR they are trading using thousands or millions of IDR in order to buy goods and this made the decimals redundant in everyday life. For instance in order to buy a loaf of bread they are spending 5.000 IDR. The amounts here are random.

If you want to handle IDR currencies without decimals you will have to implement your own `Currencies` class or initialize a `CurrencyList` class which allows you to pass your own currencies/decimals.

**Comment by frederikbosch** [comment]
@gmponos Thanks for your help here and the clear answer.
