### ISSUE TITLE
Sub-Cent Precision

### ISSUE THREAD

**Issue by Nukesor** [moneyphp/money#563]
Hi!

My company is currently trying to convert all legacy money handling to new modern MoneyPhp operations and objects, but we ran into a little problem.

The current scenario is that a customer deposits 340$ gross. We then take this amount, calculate the net amount and store this amount in our database.
`340/119×100 = 285.71429 = 285.71` since the default and proper mode is to round half away from zero
During billing creation the gross amount is recalculated, but we don't get the same amount, due to the lost precision `285.71×1.19 = 339.9949 = 339.99`. Adding a cent doesn't work either:  `285.72x1.19 = 340.0068 = 340.01`.

Changing to another rounding strategy wouldn't help either, since the rounding strategy depends on the current scenario.

One possibility for handling this properly could be to add another digit to the precision, which is used internally and returned on ->getAmount, but ignored by MoneyFormatters. `285.714×1.19 = 339.99966 = 340`.
I'm really hoping that there are some helpers in this library to achieve this behavior, but I couldn't find it yet.

The only other possibility I see right now is to completely stop using moneyphp internally and to only use it for formatting and parsing. Right now moneyphp doesn't seem to provide enough precision for reproducible division and multiplication.

I read through the docs and couldn't find a section regarding this issue. I would be really happy, if there is a way to properly handle this issue, since I like this library a LOT and it would be a shame to remove it from our internal processing again :/ !

If there is no possibility to handle something like this, it would be great, if this behavior could be added to your docs (Something like `Be careful you're losing precision due to division. MoneyPhp does not handle sub-cent values`), since it can become a problem and it's not necessarily something you would think of, when searching for a money library.

Best regards,
Arne

**Comment by UlrichEckhardt** [comment]
Why don't you store the fact that 340$ were deposited? The point is, you need that sum at some 
point and you have it to begin with. Since you are doing computations on it, you also get a loss in precision, which simply can not be recovered. Trying to solve that using more precision is limited as well. If you have multipliers with smaller fractions (e.g. 18.5%), you will not be able to construct the source value either.

BTW: In case you haven't heard of it, consider using "Event Sourcing" to model your business case. Accounting tasks like the one you seem to have are typically the prime example where event sourcing excels. In short, you only store the fact that 340$ were deposited. The net amount 285.71$ is just an interpretation. If you then need a different interpretation or the raw source value, you can compute it or just read it from your database.

**Comment by Nukesor** [comment]
If I were the one that designed this project, I would have very likely implemented it this way, but sadly, I'm operating on a huge legacy code base. We are already refactoring step by step, but cases like this are quite common.

Maybe we really need to rewrite the business logic. I just hoped to avoid this for now and come back to the issue in a later iteration.

**Comment by frederikbosch** [comment]
@Nukesor Can you point out an exact thing that is failing? It is a whole story you are telling in the description, but what exactly is the bug you found?

**Comment by Nukesor** [comment]
I would expect a money library to work without rounding errors for simple arithmetic operations. One or two fields for additional sub-cent precision would probably resolve 99% of all rounding errors.

Anyway, since implementing this behavior in moneyphp would probably be too much effort/ would not be backward compatible, I'll look around for another library.

Thank you for clarifications and sorry for any inconveniences :)
