### ISSUE TITLE
Calculate accurate tax

### ISSUE THREAD

**Issue by aniket-magadum** [moneyphp/money#590]
I am trying to calculate tax based on percentage which can be 5%, 12%, 18%.
### Current behavior
```php
$tax = 5;
$amount = 89453;
$totalAmount= $amount->multiply( $tax /100)->getAmount(); // $totalAmount= 4472
```
### What I am expecting
```php
$tax = 5;
$amount = 89453;
$totalAmount= $amount->multiply( $tax /100)->getAmount(); // $totalAmount= 4472.65
```
In short, I require exact precision in my decimal how can this be achieved .

**Comment by aniket-magadum** [comment]
I also tried the solution describe [here](https://github.com/moneyphp/money/issues/569#issuecomment-536427319) .
```php
$tax = 5;
$amount = 89453;
$taxRate = $tax/100;
$totalAmount= $amount->multiply($taxRate)->getAmount(); // $tax = 4472 not 4472.65
```

**Comment by GreenImp** [comment]
@4nik3t did you find a solution to this? I'm guessing that it's a case of having to change the rounding rule used, but not can't find any explanation as to what they all mean.

**Comment by 4nik3t** [comment]
No I didn't find a solution for this . I went with storing in cents

**Comment by UlrichEckhardt** [comment]
I'm not sure if you can edit your example code above, but they are currently calling `multiply()` on an integer, you want a Money object there instead.

Anyhow, the point of the Money library is that calculations give you results in multiples of the currency unit (which is typically a cent). You seem to want fractions of a unit, which simply defies this goal. Since you can't pay a fraction of the unit, that also doesn't make sense, you must round at some point.

**Comment by GreenImp** [comment]
@UlrichEckhardt what I'm trying to do is to store a tax exclusive value in the DB, convert it to a Money object, and then calculate the tax on it.

In this particular case, I know that the tax **inclusive** price needs to be calculated as £39.99, with tax (VAT) at 20%.
So the tax **exclusive** price should be £33.325.

I can store the decimal value `33.325` in the DB but, when converting it into a Money object, it rounds the value up `33.33`. This means that when I add the tax, it is using a slightly higher value than it should, to calculate  the gross value.

```
33.325 * 1.2 == 39.99
33.33 * 1.2 = 39.996
```

So:

```
$baseValue = Money::GBP(33.325);  // converts amount to `33.33`
$taxRate = 0.2;

$grossValue = $baseValue->multiply(1 + $taxRate);

echo $grossValue->getAMount(); // 40.00 because the trailing `6` causes the value to be rounded up.
```

I'm not sure how to get around this and calculate the correct gross amount. I'm happy for any suggestions.

**Comment by kslimani** [comment]
@GreenImp which version of `moneyphp/money` are you using ?

`$baseValue = Money::GBP(33.325);` should have throw an invalid exception. (it require an integer).

**Comment by GreenImp** [comment]
Ah yes, sorry, I'm actually using https://github.com/cknow/laravel-money which is a Laravel wrapper for Money PHP.

It has a class for automatically casting decimal values to instances of Money: https://github.com/cknow/laravel-money/blob/3431fe3663efac5db883459b55949a269cb0880b/src/MoneyCast.php#L44

```
        return Money::parseByDecimal(
            $value,
            $this->getCurrency($attributes),
            Money::getCurrencies()
        );
```

`parseByDecimal` is defined as:
```
    /**
     * Parse by decimal.
     *
     * @param string            $money
     * @param string|null       $forceCurrency
     * @param \Money\Currencies $currencies
     *
     * @return \Cknow\Money\Money
     */
    public static function parseByDecimal($money, $forceCurrency = null, Currencies $currencies = null)
    {
        $parser = new DecimalMoneyParser($currencies ?: static::getCurrencies());

        return static::parseByParser($parser, $money, $forceCurrency);
    }
```

And it's calling the `DecimalMoneyParser` defined in this package: https://github.com/moneyphp/money/blob/master/src/Parser/DecimalMoneyParser.php


So Laravel Money will take a value like `33.325` and call the decimal parser on it, which does the rounding, and parses to an `int`. IT then uses that value to create the `Money` instance.

**Comment by kslimani** [comment]
@GreenImp  I think money default behaviour is to handle [2 digits avec point for GBP currency](https://github.com/moneyphp/money/blob/master/resources/currency.php#L457) and it round the value.

Since it internally uses DecimalMoneyParser, i think a solution may be to simply override `minorUnit` for GBP currency.
(allowing 3 instead of 2, but i did not test myself).

In [laravel-money "currencies" configuration option](https://github.com/cknow/laravel-money/blob/v6.1.0/config/config.php#L12) it seems you can specify your own currencies (but never tested myself).

**Comment by GreenImp** [comment]
@kslimani thanks. I think that changing the `minorUnit` to allow 3, instead of 2 might cause formatting issues down the line.

I think that what I'm going to have to do is to store the value as an integer, like `33325`, and then either don't use Money at all, or just use it for formatting.

**Comment by kslimani** [comment]
@GreenImp i my project, i also store money value as integer to avoid floating issue and it is convenient because Money library work internally with integer. Just ensure to use Money object methods for each [operations](https://moneyphp.org/en/stable/features/operation.html) on money value instances.

**Comment by GreenImp** [comment]
Yeah, I think that's probably the right way to go. Thanks!
